name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
           record: true
           start: yarn run dev
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: <SUA CHAVE GERADA PELO CYPRESS>
